source 'https://rubygems.org'
require 'uri'
group :development do
  #gem 'spring'
  gem 'quiet_assets'
  gem 'debugger'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'rails_best_practices'
end
gem 'rails', '4.1.1'
gem 'rails_12factor'
# gem 'sqlite3'
gem 'pg'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'spring', group: :development
# gem 'bcrypt', '~> 3.1.7'
# gem 'unicorn'
# gem 'capistrano-rails', group: :development
gem 'sass-rails', '>= 3.2'
gem 'bootstrap-sass', '~> 3.1.1'
gem "rmagick"
gem "carrierwave"
gem 'kaminari'
gem 'slim-rails'
gem 'devise'
gem 'devise_invitable', '~> 1.3.4'
gem 'omniauth'
gem 'omniauth-facebook'
# gem 'omniauth-twitter'
# gem 'tinymce-rails'
# gem 'awesome_nested_set'
# gem 'acts_as_commentable_with_threading'
gem 'social-share-button'
gem 'impressionist'
gem 'activemerchant'
gem 'simple_form'
gem "font-awesome-rails"
# gem 'gmaps4rails'
# gem 'font-awesome-sass-rails'
# gem 'countries'
gem 'country_select', github: 'stefanpenner/country_select'
gem 'friendly_id', '~> 5.0.0'
gem 'stripe'
gem 'activeadmin', github: 'gregbell/active_admin'
gem "fog"
gem 'nprogress-rails'
gem 'metamagic'
ruby "2.1.1"